# configure logs
log:
  level: DEBUG # Set to 'DEBUG' for troubleshooting

# configure entry points
entryPoints:
  http:
    address: ":80"
    http:
      redirections: # http to https redirection
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

# configure providers
providers:
  docker:
    network: traefik-public
    endpoint: "unix:///var/run/docker.sock" # connection to the docker daemon
    exposedByDefault: false # ignore containers without label 'traefik.enable=true'
  file:
    directory: "/etc/traefik/conf" # directory for dynamic traefik configuration files
    watch: true # changes are processed immediately

api:
  dashboard: true # enable the traefik dashboard