[tls.stores]
[tls.stores.default]
[tls.stores.default.defaultCertificate]
certFile = "/etc/traefik/certs/local.crt"
keyFile  = "/etc/traefik/certs/local.key"

[[tls.certificates]]
certFile = "/etc/traefik/certs/traefik.local.crt"
keyFile  = "/etc/traefik/certs/traefik.local.key"